name: CI

on:
  workflow_dispatch:

jobs:
- name: Install Android NDK
  run: |
    wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
    unzip android-ndk-r25b-linux.zip
    echo "NDK_HOME=$PWD/android-ndk-r25b" >> $GITHUB_ENV
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/qgzslm/ppoomkio
          kernel-branch: master
          config: msmcortex-NX563J-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
