# .github/workflows/android_kernel_ci.yml
name: Android 9 Kernel Builder

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      ARCH: arm64
      NDK_VERSION: r20b
      KCFLAGS: "-Wno-error=array-bounds -Wno-error=unused-function"

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        repository: qgzslm/ppoomkio
        fetch-depth: 0
        submodules: recursive

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            bc \
            bison \
            build-essential \
            clang-12 \
            flex \
            lld-12 \
            llvm-12 \
            libncurses-dev \
            python2 \
            unzip
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Download NDK
      run: |
        wget -q --retry-connrefused --waitretry=30 https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip
        unzip -q android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip

    - name: Apply signal fix patch
      run: |
        cat > signal_fix.patch <<'EOL'
        diff --git a/include/linux/signal.h b/include/linux/signal.h
        index 5d9e8d7..a1b2341 100644
        --- a/include/linux/signal.h
        +++ b/include/linux/signal.h
        @@ -87,7 +87,7 @@ struct __sigqueue {
         #ifdef __ARCH_SI_PREAMBLE_SIZE
         #define SI_PAD_SIZE     ((__ARCH_SI_PREAMBLE_SIZE/sizeof(int)) - 3)
         #endif
        -#define _NSIG_WORDS (_NSIG / _NSIG_BPW)
        +#define _NSIG_WORDS 2
         
         typedef struct {
             unsigned long sig[_NSIG_WORDS];
        @@ -158,12 +158,14 @@ static inline void sigdelset(sigset_t *set, int _sig)
                 break;
             case 1:
                 set->sig[0] = op(set->sig[0]);
        +#if _NSIG_WORDS > 1
             case 2:
                 set->sig[1] = op(set->sig[1]);
        +#endif
             }
         }
         #endif /* __HAVE_ARCH_SIG_BITOPS */
        EOL
        git apply signal_fix.patch

    - name: Build kernel
      run: |
        export CLANG_PATH=$PWD/android-ndk-${{ env.NDK_VERSION }}/toolchains/llvm/prebuilt/linux-x86_64/bin
        make O=out ARCH=$ARCH msmcortex-NX563J-perf_defconfig
        make -j$(nproc) O=out ARCH=$ARCH \
            CC="$CLANG_PATH/clang" \
            LD="$CLANG_PATH/ld.lld" \
            KCFLAGS="$KCFLAGS"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: out/arch/${{ env.ARCH }}/boot/Image
